silent: false

unleash:
  threshold:
    efficacy: 60        # ≥60% of tested mutants must be killed
    mutant-coverage: 60 # skip mutants in code with <60% line coverage

mutants:
  arithmetic-base:
    enabled: true
  conditionals-boundary:
    enabled: true
  conditionals-negation:
    enabled: true
  increment-decrement:
    enabled: true
  invert-assignments:
    enabled: false
  invert-bitwise:
    enabled: false
  invert-bwassign:
    enabled: false
  invert-negatives:
    enabled: true
  invert-logical:
    enabled: true
  invert-loopctrl:
    enabled: false
  remove-self-assignments:
    enabled: false
