name: Promote Release

on:
  release:
    types: [released]

jobs:
  promote:
    uses: danielriddell21/github-actions/.github/workflows/promote.yaml@v1
    permissions:
      contents: read
      packages: write
    secrets:
      manifests-token: ${{ secrets.RIDDELLIOUS_DEV_TOKEN }}
