name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - uses: actions/create-github-app-token@v3
        id: tap-token
        with:
          app-id: ${{ vars.TAP_APP_ID }}
          private-key: ${{ secrets.TAP_APP_PRIVATE_KEY }}
          owner: danielriddell21
          repositories: homebrew-tap
      - uses: goreleaser/goreleaser-action@v7
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ steps.tap-token.outputs.token }}
          OTEL_AUTH_TOKEN: ${{ secrets.OTEL_AUTH_TOKEN }}
          OTEL_ENDPOINT: ${{ vars.OTEL_ENDPOINT }}
