name: Release

on:
  push:
    tags: ["v*"]

jobs:
  goreleaser:
    uses: danielriddell21/github-actions/.github/workflows/release.yaml@v1
    permissions:
      contents: write
      packages: write
    with:
      docker-login: true
    secrets:
      tap-app-private-key: ${{ secrets.TAP_APP_PRIVATE_KEY }}
      otel-auth-token: ${{ secrets.OTEL_AUTH_TOKEN }}
